exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: check-added-large-files
    - id: check-json
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: check-yaml
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 'master'  # Use the sha / tag you want to point at
  hooks:
  - id: shellcheck
    args:
      - --format=gcc
      - --exclude=SC2034
      - --shell=sh
  - id: markdownlint
    args:
    - -r MD046=consistent
-   repo: https://github.com/Lucas-C/pre-commit-hooks-go
    sha: v1.0.0
    hooks:
    -   id: checkmake
